[package]
name = "wild-doc-server"
version = "0.5.3"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = ""

repository = "https://github.com/OdenShirataki/wild-doc"

keywords = ["database","javascript","v8","xml","html"]
categories = ["database-implementations","network-programming","template-engine"]

license = "MIT/Apache-2.0"

[dependencies]
toml = "0.7"
serde = "1.0"
serde_derive = "1.0"
wild-doc = { version = "0.76" , path = "../wild-doc" }