[package]
name = "semilattice-script"
version = "0.1.0"
edition = "2018"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

license = "MIT/Apache-2.0"

[dependencies]
libc="0.2"
natord="1.0"
memmap2="0.5"
quick-xml="0.26"
chrono="0.4"
v8="0.54"
rustc-hash = { version = "1.0", default-features = false }
rand="0.8"

[dependencies.semilattice-database]
path = "../semilattice-database"

[dependencies.avltriee]
path = "../avltriee"

[dependencies.file_mmap]
path = "../file_mmap"

[dependencies.idx_sized]
path = "../idx_sized"

[dependencies.various_data_file]
path = "../various_data_file"

[dependencies.idx_binary]
path = "../idx_binary"