[package]
name = "wild-doc"
version = "0.67.2"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "You can read and write data using XML and output various structured documents.You can also program using javascript/TypeScript.It's Deno compatible."

repository = "https://github.com/OdenShirataki/wild-doc"

license = "MIT/Apache-2.0"

keywords = ["database","javascript","TypeScript","xml","html"]
categories = ["database","database-implementations","text-processing","web-programming","template-engine"]

[dependencies]
rustc-hash = { version = "1.0", default-features = false }
quick-xml = "0.28"
chrono = "0.4"
log = "0.4.17"
ring = "0.16.20"
deno_runtime = "0.111.0"
deno_ast = { version = "0.26.0", features = ["transpiling"] }

semilattice-database = { version = "0.58", path = "../semilattice-database" }
