[package]
name = "wild-doc"
version = "0.18.0"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "You can read and write data using XML and output various structured documents.You can also program using javascript(v8)."

repository = "https://github.com/OdenShirataki/wild-doc"

license = "MIT/Apache-2.0"

keywords = ["database","javascript","v8","xml","html"]
categories = ["database","database-implementations","text-processing","web-programming","template-engine"]

[dependencies]
rustc-hash = { version = "1.0", default-features = false }
quick-xml="0.26"
chrono="0.4"
deno_runtime = "0.88.0"
deno_ast = "0.21.0"

reqwest = { version = "0.11", features = ["blocking"] }

semilattice-database={version="0.33",path="../semilattice-database"}
