[workspace]
resolver = "2"
members = [
    "wild-doc",
    "wild-doc-server",
    "wild-doc-client-lib",
    "wild-doc-webserver",
    "wild-doc-script",
    "wild-doc-script-python"
]

[workspace.dependencies]
hashbrown = "0.14.0"
parking_lot = "0.12"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.7"
indexmap = { version = "2.0", features = ["serde"] }