[package]
name = "wild-doc"
version = "0.30.0"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "You can read and write data using XML and output various structured documents.You can also program using javascript(v8)."

repository = "https://github.com/OdenShirataki/wild-doc"

license = "MIT/Apache-2.0"

keywords = ["database","javascript","v8","xml","html"]
categories = ["database","database-implementations","text-processing","web-programming","template-engine"]

[dependencies]
rustc-hash = { version = "1.0", default-features = false }
quick-xml = "0.27"
chrono = "0.4"
log = "0.4.17"
ring = "0.16.20"
tokio = { version = "1.21.1", features = ["full"] }
deno_runtime = "0.90.0"

semilattice-database={version="0.39",path="../semilattice-database"}
