[package]
name = "wild-doc"
version = "0.13.0"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "You can read and write data using XML and output various structured documents.You can also program using javascript(v8)."

repository = "https://github.com/OdenShirataki/wild-doc"

license = "MIT/Apache-2.0"

keywords = ["database","javascript","v8","xml","html"]
categories = ["database","database-implementations","text-processing","web-programming","template-engine"]

[dependencies]
libc="0.2"
natord="1.0"
memmap2="0.5"
quick-xml="0.26"
chrono="0.4"
v8="0.55"
rustc-hash = { version = "1.0", default-features = false }
rand="0.8"

semilattice-database={path="../semilattice-database" , version="0.31"}
