[package]
name = "wild-doc-script-deno"
version = "0.11.0"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "deno for wild-doc"

repository = "https://github.com/OdenShirataki/wild-doc"

license = "MIT/Apache-2.0"

keywords = ["database","xml","html","javascript","TypeScript"]
categories = ["database","database-implementations","text-processing","web-programming","template-engine"]

[dependencies]
parking_lot.workspace = true
indexmap.workspace = true

ring = "0.16.20"
deno_runtime = "0.129"
deno_ast = { version = "0.29.5", features = ["transpiling"] }
futures = "0.3"

wild-doc-script = { version = "0.15", path = "../wild-doc-script" }