[package]
name = "wild-doc-script-deno"
version = "0.5.0"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "deno for wild-doc"

repository = "https://github.com/OdenShirataki/wild-doc"

license = "MIT/Apache-2.0"

keywords = ["database","xml","html","javascript","TypeScript"]
categories = ["database","database-implementations","text-processing","web-programming","template-engine"]

[dependencies]
serde_json.workspace = true
indexmap.workspace = true

ring = "0.16.20"
deno_runtime = "0.126"
deno_ast = { version = "0.28.0", features = ["transpiling"] }

wild-doc-script = { version = "0.5", path = "../wild-doc-script" }