[package]
name = "wild-doc-script-deno"
version = "0.1.1"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "deno for wild-doc"

repository = "https://github.com/OdenShirataki/wild-doc"

license = "MIT/Apache-2.0"

keywords = ["database","xml","html","javascript","TypeScript"]
categories = ["database","database-implementations","text-processing","web-programming","template-engine"]

[dependencies]
ring = "0.16.20"
deno_runtime = "0.124"
deno_ast = { version = "0.28.0", features = ["transpiling"] }

wild-doc-script = { version = "0.2", path = "../wild-doc-script" }